services:
  db:
    image: postgres:alpine
    restart: always
    # set shared memory limit when using docker-compose
    # this is from the default docker postgresql docs
    container_name: SA-PostgreSQL
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-db-data:/var/lib/postgresql/data
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: SA-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres-db-data:
